// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEUNT60G75S-W3XS1FcZ_sVdCw6Th2AU8',
    appId: '1:197384242805:web:07da499c6fd1019adfda3c',
    messagingSenderId: '197384242805',
    projectId: 'kaamshaala-88d4c',
    authDomain: 'kaamshaala-88d4c.firebaseapp.com',
    storageBucket: 'kaamshaala-88d4c.firebasestorage.app',
    measurementId: 'G-J8VWC8KY3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJoTXsabkVfi0soEg3NyGGgkqgshSeFcc',
    appId: '1:197384242805:android:e0654a4872185c9fdfda3c',
    messagingSenderId: '197384242805',
    projectId: 'kaamshaala-88d4c',
    storageBucket: 'kaamshaala-88d4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFpRrEkHmH2mRssGIGXyyn8Ob4IiiKu0Y',
    appId: '1:197384242805:ios:4e59285868c804c0dfda3c',
    messagingSenderId: '197384242805',
    projectId: 'kaamshaala-88d4c',
    storageBucket: 'kaamshaala-88d4c.firebasestorage.app',
    iosBundleId: 'com.example.solution',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFpRrEkHmH2mRssGIGXyyn8Ob4IiiKu0Y',
    appId: '1:197384242805:ios:4e59285868c804c0dfda3c',
    messagingSenderId: '197384242805',
    projectId: 'kaamshaala-88d4c',
    storageBucket: 'kaamshaala-88d4c.firebasestorage.app',
    iosBundleId: 'com.example.solution',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEUNT60G75S-W3XS1FcZ_sVdCw6Th2AU8',
    appId: '1:197384242805:web:3ccf4f347270b253dfda3c',
    messagingSenderId: '197384242805',
    projectId: 'kaamshaala-88d4c',
    authDomain: 'kaamshaala-88d4c.firebaseapp.com',
    storageBucket: 'kaamshaala-88d4c.firebasestorage.app',
    measurementId: 'G-HD6R7ZSFSZ',
  );
}
